### ISSUE TITLE
Drivers line is incorrect

### ISSUE THREAD

**Issue by HeyZeus-Tech** [AdamGrossTX/Windows10FeatureUpdates#1]
https://github.com/AdamGrossTX/Windows10FeatureUpdates/blob/1a2725d45534c91abd85bda91bdf95d9c7b11177/Admin/ComplianceScripts/FeatureUpdateCIScript.ps1#L61

"Drivers" should be "InstallDrivers"
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-setup-command-line-options

**Comment by AdamGrossTX** [comment]
Thanks for the info. I've updated the script.
