### ISSUE TITLE
Feature Request:  Versioning for Application Detection Method

### ISSUE THREAD

**Issue by Chadwicksracing** [AdamGrossTX/Windows10FeatureUpdates#17]
Put a flat file in the application that keeps track of the version your machines are suppose to be on,  You know your files are on the right version of the application

I found that my scripts were out of date of a several devices, making it difficult to troubleshoot.

**Comment by AdamGrossTX** [comment]
The GUID in the app command line should be updated each time that you update script contents. The GUID folder is what the detection method uses to verify that you have the correct version of the scripts. This should also be updated in the CI to match your new GUID.

**Comment by Chadwicksracing** [comment]
Thanks Adam
Chad Brower
Information Technology
Windows Administration & Web Developer
Founder of ST Nation
Phone: 989-750-4300


CONFIDENTIAL NOTICE:
This e-mail message and any attachment(s) (collectively, this 'Email') are
intended only for the confidential use of the recipient(s) named above. If
the reader of this message is not the intended recipient or an agent
responsible for delivering it to the intended recipient named above, you
have received this Email in error. Please notify the sender immediately and
permanently delete this Email and any copies thereof.
