### ISSUE TITLE
Authenticated Users have Modify permissions on ~FeatureUpdateTemp

### ISSUE THREAD

**Issue by astratom** [AdamGrossTX/Windows10FeatureUpdates#19]
Hey,

Just noticed that Authenticated Users have Modify permissions on the ~FeatureUpdateTemp folder. This presents a security risk as any user can modify the scripts and they'll run as SYSTEM.

Here's a short PS script to disable inheritance and remove the permissions for Authenticated Users:
```
$Folder = "$env:SystemDrive\~FeatureUpdateTemp"
$ACL = Get-Acl -Path $Folder
$ACL.SetAccessRuleProtection($True, $True) # Remove inheritance 
$ACL.Access | Where-Object {$_.IdentityReference -eq 'NT AUTHORITY\Authenticated Users'} | ForEach {$acl.RemoveAccessRule($_)} # Remove all ACLs for Authenticated Users
Set-ACL -Path $Folder -AclObject $ACL # Apply ACL on folder
```

**Comment by AdamGrossTX** [comment]
Thanks for this. I would love to store the scripts in a system folder like c:\Windows or c:\programdata but these get moved/removed during the FU so the scripts need to exist in a separate folder. 

I'll take a look. Feel free to do a PR if you want to update the code.
