### ISSUE TITLE
Feature Request: Language Packs

### ISSUE THREAD

**Issue by boozeman** [AdamGrossTX/Windows10FeatureUpdates#20]
How the language packs handled in servicing update now? Back to 1809 days there was those .cabs and /installlangpacks switch in SetupConfig.ini

**Comment by AdamGrossTX** [comment]
SetupConfig.ini still supports language packs. You just need to edit the CI to add the entry to enable them, then deploy the cabs via an app or package. I don't have plans to extend the framework to add additional functionality beyond what's already included in the ini CI.
