### ISSUE TITLE
Latest "bug fixes" (03/09/20) has broken a few things.

### ISSUE THREAD

**Issue by StevybSC** [AdamGrossTX/Windows10FeatureUpdates#7]
Hi Adam,
I've just tried re-downloading the zip with your latest fixes and it appear a few things are broken.

The SetupFUFramework.ps1 when run from the commandline with parameters ignores the application folder parameter and copies to the root. Manually editing the script, editing the param defaults and running with no switches works.

However, on running it fails on creating the "Feature Update Files" CI part.

 + Creating Feature Update - Feature Update Files Configuration Item..  X
########################################################
The following error occurred:
 + Cannot validate argument on parameter 'Path'. System.Management.Automation.ValidationMetadataException
 + Line: 598
########################################################
Add-CMComplianceSettingFile : Cannot validate argument on parameter 'Path'.
System.Management.Automation.ValidationMetadataException
At C:\Temp\IPU\SetupFUFramework.ps1:598 char:59
+ ... FilesCI | Add-CMComplianceSettingFile @FUFilesCIScriptsExistsSettings
+                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-CMComplianceSettingFile], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.ConfigurationManagement.Cmdlets.Dcm.Commands.
   AddComplianceSettingFileCommand

Just thought I'd log it and I'm looking into it properly now.

**Comment by AdamGrossTX** [comment]
Can you share your commandline that your using?  I'm testing from a commandline and not seeing the same issues

`.\SetupFUFramework.ps1 -SiteCode "PS1" -ProviderMachineName "CM01.ASD.NET" -ApplicationFolderName "FUApplication" -ContentLocation "\\CM01.ASD.NET\Media\$($ApplicationFolderName)" -NetworkLogPath "\\CM01.ASD.NET\FeatureUpdateLogs" `

This is what I'm using.

**Comment by AdamGrossTX** [comment]
Ok @StevybSC I found the issue with the error message you listed and have published the fix for that. However, I can't repro the ApplicationFolderName issue. Please provide more details.

**Comment by StevybSC** [comment]
Hi Adam,
I just came back to add some more details only to see you beat me to the fix with the parent.fullname 👍 

I've been testing in VSCode line by line so haven't cycled back to the ApplicationFolderName issue yet, will go try that in a minute.

Couple of other things I've picked up on (I really need to learn how to do a pull request...)

If the folder doesn't exist on the network share the copy section writes the scripts dir to the root instead of the Scripts directory.
Don't know why, but it does.

Quick and dirty check and create before the copy works.

`
    Write-Host " + Copying files to $($ContentLocation)" -ForegroundColor Cyan -NoNewline
    if (!(Test-Path filesystem::$ContentLocation)) {
        New-Item -Path (Split-Path $ContentLocation) -Name $ApplicationFolderName -ItemType Directory | Out-Null
    }
    Get-ChildItem -Path $NewAppPath | Copy-Item -Destination $ContentLocation -Force -Recurse -ErrorAction Stop
    Write-Host $Script:tick -ForegroundColor green
`

The variables in the "Additional info" section at the end of the script are wrong. I've also encapsulated in [ ] for better readability.

`
    Write-Host " -- Deploy the Configuration Baseline [$($NoLoggedOnUserBaseline.Name)] to all Windows 10 devices." -ForegroundColor Cyan
    Write-Host " -- Deploy the Configuration Baseline [$($InventoryBaseline.Name)] to all Windows 10 devices." -ForegroundColor Cyan
`

Epic work btw, I'm looking forward to testing properly tomorrow!
I'll go check the app folder via switch now.

**Comment by StevybSC** [comment]
Command line:
.\SetupFUFramework.ps1 -SiteCode "PON" -ProviderMachineName "PONCONFIGMGR01.PowerON.local" -ApplicationFolderName "WaaSServicing" -ContentLocation "\\PONDML\Apps\WaaS\$($ApplicationFolderName)" -NetworkLogPath "\\PONDML\Apps\FeatureUpdateLogs"

Expected app source folder = \\PONDML\Apps\WaaS\WaaSServicing
Actual app source folder = \\PONDML\Apps\WaaS

![image](https://user-images.githubusercontent.com/39970719/92181798-0b1e2a80-ee42-11ea-9182-c424f4cb94c4.png)

**Comment by AdamGrossTX** [comment]
Awesome info. I’ll take a look at your notes later tonight.

Adam Gross
A Square Dozen
Blogger-In-Chief
Twitter: AdamGrossTX
http://www.asquaredozen.com
________________________________

**Comment by StevybSC** [comment]
Thinking about it, I think it's more to do with me copying your example command and not thinking about it.

I'm unsure if it will pass $ApplicationFolderName through to be parsed inside the script, instead it will evaluate the variable using the context of the current session, which doesn't have a value for that variable, hence it passing null.

Feel free to test, but I think it's a can't fix / not a bug.  Easier to just hardcode the path on the switch.

**Comment by AdamGrossTX** [comment]
The sample that I posted above is what I was testing with from a PS 5.1 cmdline and it creates the nw folder. If you’re testing with 5.1 in VSCode you may see issues     - like PSScriptRpot is blank,etc. try in a straight PS window or use PS 7.1 on VSCode.

Adam Gross
A Square Dozen
Blogger-In-Chief
Twitter: AdamGrossTX
http://www.asquaredozen.com
________________________________

**Comment by StevybSC** [comment]
Sorry, should have been clearer.
I only get the error when running from normal PS window (screen shot in comment above).

**Comment by AdamGrossTX** [comment]
I was able to repro last night. Thanks for finding this one. Should be fixed now. 

You mentioned something about bad variable names at the end. Please let me know in a new issue what you found there.

**Comment by AdamGrossTX** [comment]
Note, the parameter names have changed now...

`    .\SetupFUFramework -SiteCode "PS1" -SiteServer "CM01.ASD.NET" -ApplicationFolderName "FUApplication" -ApplicationSourceRoot "\\CM01.ASD.NET\Media\$($ApplicationFolderName)" -NetworkLogPath "\\CM01.ASD.NET\FeatureUpdateLogs"`
