### ISSUE TITLE
Baseline [Feature Update - Scripts and Files Are Present] fails compliance

### ISSUE THREAD

**Issue by StevybSC** [AdamGrossTX/Windows10FeatureUpdates#8]
The SetupFUFramework.ps1 script creates the [Feature Update - Feature Update Files] Configuration Item with two settings for folder existence checks, however it appears to create them as file type checks.

![image](https://user-images.githubusercontent.com/39970719/92234441-f6757d00-eea9-11ea-8b7a-c440a2b3b9fa.png)

The baseline then fails compliance, even though the folders exist.
Manually removing and recreating as folder types then passes compliance.
![image](https://user-images.githubusercontent.com/39970719/92234522-1e64e080-eeaa-11ea-94e6-b2a02d925491.png)

If this is supposed to be a folder and not file check, the following would need adjusting:
`    $FUFilesCIUpdateFilesExistsSettings = @{
        FileName = $FUFilesGUID`
to
`    $FUFilesCIUpdateFilesExistsSettings = @{
        DirectoryName = $FUFilesGUID`

`    $FUFilesCIScriptsExistsSettings = @{
        FileName = $ScriptsPath.BaseName`
to
`    $FUFilesCIScriptsExistsSettings = @{
        DirectoryName = $ScriptsPath.BaseName`

and
`    $FUFilesCI = $FUFilesCI | Add-CMComplianceSettingFile @FUFilesCIUpdateFilesExistsSettings
    $FUFilesCI = $FUFilesCI | Add-CMComplianceSettingFile @FUFilesCIScriptsExistsSettings`
to
`    $FUFilesCI = $FUFilesCI | Add-CMComplianceSettingDirectory @FUFilesCIUpdateFilesExistsSettings
    $FUFilesCI = $FUFilesCI | Add-CMComplianceSettingDirectory @FUFilesCIScriptsExistsSettings`

Potentially the `IncludeSubfolders = $True` settings to $false?

**Comment by AdamGrossTX** [comment]
I fixed that issue yesterday afternoon. Please try again and reopen the issue if it isn't resolved.

https://github.com/AdamGrossTX/Windows10FeatureUpdates/commit/1173848fde697c3a5a4a9a06b0eae4bf96d3bcc1
